<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

$this->borderContainer()->captureStart('searchC', array('design' => 
    'headline', 'style' => 'padding: 0px; margin: 0px; border: 0px;'));

$this->contentPane()->captureStart('searchopts', array('region' => 'top', 
    'style' =>'height: 130px; padding: 0px; margin: 0px; border: 1px solid #ccc;'));
echo $this->render('search/searchoptions.phtml');
echo $this->contentPane()->captureEnd('searchopts');


$this->contentPane()->captureStart('searchrset', array('region' => 'center', 
    'style' =>'padding: 0px; margin: 0px; border: 1px solid #ccc;', 'href' => '/default/search/runsearch'));
echo $this->contentPane()->captureEnd('searchrset');

echo $this->borderContainer()->captureEnd('searchC');

