<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
?>
<div class="note">
You are about to delete the branch with DN : <?php echo $this->entry->getdn();?>
</div>

<div class="alert">
<P class="heading">
Are you sure you want to delete Branch <em><?php echo $this->entry->getProperty('cn');?>?</em>
</P>
<div style="margin-left: 10px;font-weight: normal; color: blue;">
    <button dojoType="dijit.form.Button" id="confirm">Delete
        <script type="dojo/method" event="onClick">
        zivios.callAction('/locality/deletebranch',{confirm: true,dn: '<?php echo $this->entry->getdn();?>'},'confirm');
        </script>
    </button>
</div>
</div>


