<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/


$this->borderContainer()->captureStart('bulkimportmain',array('design' =>
    'headline','style' => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

$this->contentPane()->captureStart('bulkimportmaintop', array('region' => 'top', 
    'style' =>'height: 250px; padding: 0px; margin: 0px; '));

$this->borderContainer()->captureStart('bulkimport', array('design' => 
    'sidebar', 'style' => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

$this->contentPane()->captureStart('bulkimportform', array('region' => 'left',
    'style' =>'width: 450px; padding: 0px; margin: 0px; border: 0px;'));
echo $this->render('import/mainform.phtml');
echo $this->contentPane()->captureEnd('bulkimportform');

$this->contentPane()->captureStart('bulkimportcsv', array('region' => 'right',
    'style' =>'padding: 0px; margin: 0px; border: 1px solid #e5e5e5; '));
echo $this->render('import/importcsv.phtml');
echo $this->contentPane()->captureEnd('bulkimportcsv');

echo $this->borderContainer()->captureEnd('bulkimport');
echo $this->contentPane()->captureEnd('bulkimportmaintop');
$this->contentPane()->captureStart('searchdata', array('region' => 'center',
    'style' => 'padding: 0px; margin: 0px;'));

// Info cpane.
echo '<div class="info infocl" style="margin-left: 10px; width: 350px;">Search 
    results will appear here for import selection into the Zivios tree.</div>';
echo $this->contentPane()->captureEnd('searchdata');
echo $this->borderContainer()->captureEnd('bulkimportmain');

