<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/

$this->borderContainer()->captureStart('sedashboard01', array(
    'design' => 'sidebar',
    'style'  => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

    $this->contentPane()->captureStart('sesysdetails', array(
        'region' => 'left', 
        'style'  => 'width: 420px; padding: 0px; margin: 0px; border: 0px; border-right: 1px solid #ccc;'));
    echo $this->render('server/entry/linux/dashboard/sysdetails.phtml');
    echo $this->contentPane()->captureEnd('sesysdetails');

    $this->contentPane()->captureStart('secontrolmon', array(
        'region' => 'center', 
        'style'  => 'padding: 0px; margin: 0px; border: 0px; border-left: 1px solid #ccc; border-bottom: 1px solid #ccc;'));
    echo $this->render('server/entry/linux/dashboard/sysmonitor.phtml');
    echo $this->contentPane()->captureEnd('secontrolmon');

    $this->contentPane()->captureStart('secontrolsecurity', array(
        'region' => 'bottom', 
        'style'  => 'height: 250px; padding: 0px; margin: 0px; border: 1px solid #ccc; border-right: 0px; border-bottom: 0px;'));
    echo $this->render('server/entry/linux/dashboard/syssecurity.phtml');
    echo $this->contentPane()->captureEnd('secontrolsecurity');

echo $this->borderContainer()->captureEnd('sedashboard01');

