<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_asterisk
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/

 
$formid   = Zivios_Util::randomString(8);
$regexLib = Zivios_Util::getRegexLibrary();
$user = $this->user;
$plugin = $this->plugin
?>

<div class="subheading">Activate Asterisk Plugin</div>
<div class="content">
    <form id='<?php echo $formid; ?>' enctype="application/x-www-form-urlencoded" method="post" 
        action="#" dojoType="dijit.form.Form">
     <fieldset>
    
     
    <div class="labell">Extension: </div>

    <input dojoType="dijit.form.ValidationTextBox" value="" style="width: 100px;" required="true"
        name="ast[rq_digits_astexten_Asterisk+Extension]" class="genField" />
    <div class="cboth"></div>

    <div class="labell">Context: </div>
    <input dojoType="dijit.form.ValidationTextBox" style="width: 200px;" value="from-sip" name="ast[rq_postaladdress_context_Sip+Context]" 
    	class="genField"/>
    <div class="cboth"></div>
    
    <div class="labell">Phone Password: </div>
    <input dojoType="dijit.form.ValidationTextBox" value="" name="ast[op_alnumnospaces_password_Phone+Password]" class="genField"/>
    <div class="cboth"></div>
    
    <div class="labell">Allowed Codecs</div>
    <input dojoType="dijit.form.CheckBox" value="ulaw" name="ast[op_noval_codecs_Allowed+Codecs][]" class="genField"/>-ulaw
    <input dojoType="dijit.form.CheckBox" value="alaw" name="ast[op_noval_codecs_Allowed+Codecs][]" class="genField"/>-alaw
    <input dojoType="dijit.form.CheckBox" value="gsm" name="ast[op_noval_codecs_Allowed+Codecs][]" class="genField"/>-gsm
    <input dojoType="dijit.form.CheckBox" value="g729" name="ast[op_noval_codecs_Allowed+Codecs][]" class="genField"/>-g729
    <div class="cboth"></div>
    <div class="labell">Allowed Routes: </div>
    <?php
    $allroutes = $plugin->getService()->getObRoutes();
    $userroutes = $plugin->getProperty('emsastroutesallowed');
    foreach ($allroutes as $route) {
    	$selected = 'false';
    	if (in_array($route,$userroutes)) {
    		$selected = 'true';
    	}
    	?>
    	<input dojoType="dijit.form.CheckBox" value="<?php echo $route;?>" checked="<?php echo $selected;?>" name="ast[op_noval_routes_Allowed+Routes][]"
    		class="genField" /> <?php echo $route;?>
    	<?php
    }
    ?>
    <div class="cboth"></div><br />
    <?php
    $disabled = 'false';
    if ($plugin->getProperty('emsastdisable') == "1")
    {
    	$disabled = 'true';
    }
    ?>
    
    <?php
    $canreinvite = 'false';
    if ($plugin->getProperty('astaccountcanreinvite') == "yes")
    {
    	$canreinvite = 'true';
    }
    ?>
    <div class="labell">Can SIP Reinvite Enabeld?: </div>
    <input dojoType="dijit.form.CheckBox" value="1" checked="<?php echo $canreinvite;?>" name="ast[op_noval_canreinvite_canreinvite]" class="genField" />
    <div class="cboth"></div><br />
    <div class="labell">Phone Disabled : </div>
    <input dojoType="dijit.form.CheckBox" value="1" checked="<?php echo $disabled;?>" name="ast[op_noval_disabled_disabled]" class="genField" />
    <div class="cboth"></div><br />
    <div class="labell">Qualify Time (sec) :</div>
    <input dojoType="dijit.form.ValidationTextBox" style="width:100px;" required="false" value="<?php echo $plugin->getProperty('astaccountqualify');?>" 
    			name="ast[op_digits_qualify_Qualify+Time]" class="genField"/>
    <div class="cboth"></div><br />
    <br />
    <?php
    $vmenable = 'false';
    if ($plugin->getProperty('emsastvoicemailenabled') == "1")
    {
    	$vmenabled = 'true';
    }
    ?>
    <div class="labell">VoiceMailbox Enabled: </div>
    <input dojoType="dijit.form.CheckBox" value="1" checked="<?php echo $vmenabled;?>" name="ast[op_noval_vmenabled_vmenabled]" class="genField" />
    <div class="cboth"></div><br />
    <div class="labell">Voicemailbox Password :</div>
    <input dojoType="dijit.form.ValidationTextBox" style="width:100px;" required="false" value="<?php echo $plugin->getProperty('astvoicemailpassword');?>" 
    			name="ast[op_digits_vmpassword_VoiceMail+Password]" class="genField"/>
    <div class="cboth"></div><br />
    
    <input onclick="zivios.postxhr('/asterisk/user/doactivateplugin', '', '<?php echo $formid; ?>',
        'form', 'json', [], [], [], [], this.id); return false;" 
        name="inica" value="Activate" 
        type="submit" label="Activate" dojoType="dijit.form.Button"/>
    <div class="cboth"></div>

    <input type="hidden" name="ast[rq_noval_dn_dn]" value="<?php echo $user->getdn();?>"/>

	</fieldset>
    </form>
</div>
 
