<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_ldap
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/

// Toolbar cpane
$this->contentPane()->captureStart('ldapconftb', array(
    'region' => 'top',
    'style' => 'width: 100%; height: 24px; padding: 0px; margin: 0px; border: 1px solid #e5e5e5;'));
    echo $this->render('service/toolbars/configtb.phtml');
echo $this->contentPane()->captureEnd('ldapconftb');

// Load default info page
$this->contentPane()->captureStart('ldapconfdata', array(
    'region' => 'center',
    'style' => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));
    echo $this->render('service/config/info.phtml');
echo $this->contentPane()->captureEnd('ldapconfdata');

