<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
$regex = Zivios_Regex::loadLibrary();
?>
<div class="note"> You can add a custom transport below </div>

<form action="#" method="post" id="addtransportform" dojoType="dijit.form.Form" onsubmit="return false;">
    <input type="hidden" name="dn" value="<?php echo $this->dn;?>"/>
    <input type="hidden" name="changeaction" value="add"/>
    
    <div style="padding-left: 5px; float: left;">
        <Label for="transport"><B>Domain: </b> </label>
        <input type="text" dojoType="dijit.form.ValidationTextBox" name="domain" id="domain" 
        regExp="<?php echo $regex->exp->hostname;?>" required="true" invalidMessage="Invalid Transport Domain">
    </div>
    <div style="float: left;">
        <Label for=""><B>Destination: </b> </label>
        <input type="text" dojoType="dijit.form.ValidationTextBox" name="destination" id="destination" 
        regExp="<?php echo $regex->exp->hostname;?>" required="true" invalidMessage="Invalid Transport Destination">
    </div>
    <div style="float: left;">
        <Label for=""><B>Tranport Type: </b> </label>
        <select type="text" dojoType="dijit.form.FilteringSelect" name="type" id="type" required="true">
            <option value="relay" selected="selected">relay</option>
            <option value="smtp">smtp</option>
        </select>
    </div>
    
    <div style="width: 26%; float: left;">
    <button id="addtransportform-submit" dojoType="dijit.form.Button" label="Add Transport" disabled="true">
        <script type="dojo/method" event="onClick"> 
            zivios.formXhrPost('addtransportform', '/mail/service/dochangetransports');
        </script>
    </button>
    
    </div>
    <div style="clear: both;"></div>
</form>
