<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_samba
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id$
 * @lastchangeddate $LastChangedDate$
 **/

$browseable = '';
$writeable = '';
$guestok = '';

if ($this->obj->getProperty('emssharecfgbrowseable') != null) $browseable = 'CHECKED';
if ($this->obj->getProperty('emssharecfgwriteable') != null) $writeable = 'CHECKED';
if ($this->obj->getProperty('emssharecfgguestok') != null) $guestok = 'CHECKED';
?>
<div class="info">Share Description</b>
</div>
<br />
<form id="editshare" name="editshare" method="post" action="#" onsubmit="return false;"
	style="padding-left: 0px;">


<input type="hidden" name="operate_dn" value="<?php echo $this->obj->getdn();?>" />
<input type="hidden" name="action" value="update" />

<fieldset>
    <legend>Share Details</legend>
    <label>Name: </label>
    <input type="text" size="32" name="cn" value="<?php echo $this->obj->getProperty('cn');?>"/>
    <br />

    <label>Share Path: </label>
    <input type="text" size="32" name="path" value="<?php echo $this->obj->getProperty('emssharepath');?>"/>
    <br />

    <label>Share Comment: </label>
    <input type="text" size="32" name="comment" value="<?php echo $this->obj->getProperty('emssharecfgcomment');?>"/>
    <br />

    <label>Share Browseable? </label>
    <input type="checkbox" name="browseable" value='yes' <?php echo $browseable;?>/>
    <br />

    <label>Share Writeable? </label>
    <input type="checkbox" name="writeable" value='yes' "<?php echo $writeable;?>"/>
    <br />

    <label>Allow Guests? </label>
    <input type="checkbox" name="guestok" value='yes' "<?php echo $guestok;?>"/>
    <br />


<input type="submit" value="Apply"
	onclick="javascript:callFormUpdate('editshare', '/samba/share/edit/');" />
    </fieldset>
</form>
