<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/

// start border layout container.
$this->borderContainer()->captureStart('squidgrpmembers', array(
    'design' => 'headline',
    'style' => 'width: 100%; padding: 0px; margin: 0px;'));

    $this->contentPane()->captureStart('squidgrpmemstop', array(
        'region' => 'top', 
        'style' => 'width: 100%;padding: 0px; margin: 0px; height: 170px; border: 0px;',
        'refrshOnShow' => 'false',
        'href' => '/squid/group/memberactivationstatus/dn/'.urlencode($this->entry->getdn())));

    echo $this->contentPane()->captureEnd('squidgrpmemstop');

    $this->contentPane()->captureStart('squidgrpmemscenter', array(
        'region' => 'center',
        'style' => 'width: 100%; padding: 0px; margin: 0px; border: 0px; border-top: 1px solid #ccc;', 
        'refreshOnShow' => 'false',
        'href' => '/squid/group/getactivemembers/dn/'.urlencode($this->entry->getdn())));
    echo $this->contentPane()->captureEnd('squidgrpmemscenter');

// End border container layout
echo $this->borderContainer()->captureEnd('squidgrpmembers');
