<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		ZiviosInstaller
 * @copyright	Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

$formid   = Zivios_Util::randomString(8);
$regexLib = Zivios_Util::getRegexLibrary();
?>
<div class="heading">OpenLDAP Initialization</div>

<div class="content">
    Zivios is ready to initialize the OpenLDAP Directory Service. The OpenLDAP Directory
    houses information regarding networks, computers, users, groups and services for Zivios.
    <br /><br />
</div>

<div class="subheading">OpenLDAP Details</div>
<div class="content">
    <form id='<?php echo $formid; ?>' enctype="application/x-www-form-urlencoded" method="post" 
        action="#" dojoType="dijit.form.Form">

    <label>Short Company Name: </label>
    <input name="ldapsetup[rq_alnumnospaces_scompany_Short+Company+Name]" type="text" dojoType="dijit.form.ValidationTextBox" size="16"
            regExp="<?php echo $regexLib->exp->hostname; ?>" required="true" maxlength="8"
            invalidMessage="Invalid characters in Short Company Name" class="genField" 
            value="" />
    <div class="cboth"></div>

    <label>Base DN: </label>
    <input name="ldapsetup[rq_dn_basedn_Base+DN]" type="text" dojoType="dijit.form.ValidationTextBox" size="16"
            regExp="<?php echo $regexLib->exp->dn; ?>" required="true" maxlength="70"
            invalidMessage="Invalid characters in Base DN" class="genField" 
            value="<?php echo $this->localSysInfo['basedn']; ?>" disabled="true" />
    <div class="cboth"></div>

    <label>Zivios Admin Login: </label>
    <input name="ldapsetup[rq_uid_zauser_Zivios+Admin+Login]" type="text" dojoType="dijit.form.ValidationTextBox" size="16" maxlength="64" 
            regExp="<?php echo $regexLib->exp->uid;?>" required="true" 
            invalidMessage="Invalid characters in DB Admin User" class="genField" 
            value="zadmin" disabled="true" />
    <div class="cboth"></div>

    <label>Zivios Admin Password: </label>
    <input name="ldapsetup[rq_password_zadminpass_Zivios+Admin+Password]" type="password" dojoType="dijit.form.ValidationTextBox" size="16" maxlength="64" 
            regExp="<?php echo $regexLib->exp->password; ?>" required="true" 
            invalidMessage="Invalid password. Should be at least 3 characters." class="genField" 
            value="" />
    <div class="cboth"></div>

    <label>Confirm Password: </label>
    <input name="ldapsetup[cmp_zadminpass_czadminpass_Confirm+Zivios+Admin+Password]" type="password" dojoType="dijit.form.ValidationTextBox" size="16" maxlength="64" 
            regExp="<?php echo $regexLib->exp->password; ?>" required="true" 
            invalidMessage="Invalid password. Should be at least 3 characters." class="genField"
            value="" />
    <div class="cboth"></div>

    <div class="info" style=" margin-left: 50px; width: 450px;">Configuration (cn=config) and Replication passwords are stored internally by Zivios. Please make a personal note
        of your passwords.</div>

    <label>cn=config Password: </label>
    <input name="ldapsetup[rq_password_cnconfigpass_Configuration+Password]" type="password" dojoType="dijit.form.ValidationTextBox" size="16" maxlength="64" 
            regExp="<?php echo $regexLib->exp->password; ?>" required="true" 
            invalidMessage="Invalid password. Should be at least 3 characters." class="genField" 
            value="" />
    <div class="cboth"></div>

    <label>Replicator Password: </label>
    <input name="ldapsetup[rq_password_replicatorpass_Replicator+Password]" type="password" dojoType="dijit.form.ValidationTextBox" size="16" maxlength="64" 
            regExp="<?php echo $regexLib->exp->password; ?>" required="true" 
            invalidMessage="Invalid password. Should be at least 3 characters." class="genField" 
            value="" />
    <div class="cboth"></div>

    <label></label>
    <input onclick="installer.postxhr('/installer/index/processinildap', '', '<?php echo $formid; ?>',
        'form', 'json', [], ['loadingmsg'], ['loadingmsg'], [], this.id); return false;" 
        name="inildap" value="Initialize Directory Service" 
        type="submit" label="Initialize Directory Service" dojoType="dijit.form.Button"/>
    <div class="cboth"></div>

    </form>
</div>

