<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		ZiviosInstaller
 * @copyright	Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
?>

<div class="heading">Welcome to Zivios Installation</div>
<div class="content">
    Zivios is ready to begin probing your system for compatibility. The right side
    of this screen will print installation notes as you progress through the installation
    process.
    <br /><br />
    <button dojoType="dijit.form.Button" type="button">
        Probe Zivios Server 
        <script type="dojo/method" event="onClick" args="evt">
            installer.getxhr('/installer/index/probeserver', 'primaryContent', '', 'text', [], 
                ['loadingmsg'], ['loadingmsg'], [], true, false, this.id);
        </script>
    </button>
</div>

