<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

$formid   = Zivios_Util::randomString(8);
$regexLib = Zivios_Util::getRegexLibrary();
?>
<div dojoType="dijit.layout.TabContainer" id="tc_addbranch" class="u-tab">
    <div id="cp_addbranch" dojoType="dijit.layout.ContentPane" title="Add Branch Office" 
        selected="true" style="width: 100%; padding: 0px; margin: 0px; border: 0px;">

        <div class="heading">Branch Offices in your Organizational Tree</div>

        <div class="content">
            <div class="info infocl" style="width: 500px;">
                A Branch Office container allows the provision of User, Group and Computer Containers.
                Ideally, Branch Office containers would sit inside Locality containers.
                <br /><br />
                For additional information regarding Branch Office containers and Zivios hierarchies,
                please consult the <a href="http://wiki.zivios.org" target="_blank">Zivios Wiki</a>.
            </div>
        </div>

        <div class="subheading">Add a Branch Office</div>
        <div class="content">

        <div class="note notecl" style="width: 500px;">
            Parent DN: <?php echo $this->parentdn; ?>
        </div>

        <form id='<?php echo $formid; ?>' enctype="application/x-www-form-urlencoded" method="post" 
            action="#" dojoType="dijit.form.Form">

        <div class="zflabel" style="width: 140px;">Branch Name: </div>
        <input name="branchdata[rq_alnumwithspaces_cn_Branch+Name]" type="text" dojoType="dijit.form.ValidationTextBox" 
            size="16" maxlength="64" regExp="<?php echo $regexLib->exp->alnumwithspaces; ?>" required="true" 
            invalidMessage="Invalid characters. Only alphabets, numbers and spaces are permitted." class="zfgenField" 
            value="" />
        <div class="cboth"></div>

        <div class="zflabel" style="width: 140px;">Telephone Number: </div>
        <input name="branchdata[rq_phonenumber_telephonenumber_Telephone+Number]" type="text" dojoType="dijit.form.ValidationTextBox" 
            size="16" maxlength="64" regExp="<?php echo $regexLib->exp->phonenumber; ?>" required="true" 
            invalidMessage="Invalid characters. Only digits and dashes are permitted." class="zfgenField" 
            value="" />
        <div class="cboth"></div>

        <div class="zflabel" style="width: 140px;">Fax Number: </div>
        <input name="branchdata[rq_phonenumber_facsimiletelephonenumber_Fax+Number]" type="text" dojoType="dijit.form.ValidationTextBox" 
            size="16" maxlength="64" regExp="<?php echo $regexLib->exp->phonenumber; ?>" required="true" 
            invalidMessage="Invalid characters. Only digits and dashes are permitted." class="zfgenField" 
            value="" />
        <div class="cboth"></div>
        
        <div class="zflabel" style="width: 140px;">Branch Code: </div>
        <input name="branchdata[op_alnumwithspaces_emscode_Branch+Code]" type="text" dojoType="dijit.form.ValidationTextBox" 
            size="16" maxlength="64" regExp="<?php echo $regexLib->exp->alnumwithspaces; ?>" required="false" 
            invalidMessage="Invalid characters. Only alphabets, numbers and spaces are permitted." class="zfgenField" 
            value="" />
        <div class="cboth"></div>


        <div class="zflabel" style="width: 140px;">Branch Address: </div>
        <input name="branchdata[rq_postaladdress_postaladdress_Branch+Address]" type="text" dojoType="dijit.form.SimpleTextarea" style="width: 220px; height: 80px;" 
            class="zfgenField" required="true" value=""/>
        <div class="cboth"></div>

        <div class="zflabel" style="width: 140px;">&nbsp;</div>
        <input onclick="zivios.postxhr('/default/locality/doaddbranch', '', '<?php echo $formid; ?>',
            'form', 'json', [], [], [], [], this.id); return false;" 
            name="zvaddbranch" value="Add Branch Office" 
            type="submit" label="Add Branch Office" dojoType="dijit.form.Button"/>
        <div class="cboth"></div>

        <input type="hidden" name="branchdata[rq_dn_dn_Distinguished+Name_enc]" value="<?php echo urlencode($this->parentdn); ?>"/>
        </form>
        </div>
    </div>
</div>

