<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
?>
<div dojoType="dijit.layout.BorderContainer" design="headline" gutters="false" liveSplitters="false" id="viewbranchlocalityentry">
    <div dojoType="dijit.layout.ContentPane" splitter="false" region="top" id="ltb01" style="margin-bottom: 5px;">
        <?php echo $this->render('branch/toolbar/ltb01.phtml'); ?>
    </div>

    <div dojoType="dijit.layout.ContentPane" splitter="false" region="center" id="localitydata">
        
        <div dojoType="dijit.layout.TabContainer" style="width: 100%; height: 100%;" id="localitytabs">
            <div dojoType="dijit.layout.ContentPane" title="Branch Office Dashboard" selected="true" 
                id="localityfirst">
                <?php echo $this->render('branch/dashboard/main.phtml'); ?>
            </div>
        </div>

    </div>
</div>

