<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

// start border layout container for locality entry.
$this->borderContainer()->captureStart('customcontainer', array('design' => 'headline', 
    'style' => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

// Content pane for toolbar
$this->contentPane()->captureStart('cctb01', array('region' => 'top', 'style' => 'width: 100%; 
    padding: 0px; margin: 0px; border: 0px;'));
echo $this->render($this->cctb01);
echo $this->contentPane()->captureEnd('cctb01');
// Content pane for toolbar ends above.

$this->contentPane()->captureStart('cclayout', array('region' => 'center', 'style' => 
    'width: 100%; padding: 0px; margin: 0px; border: 0px;'));
$this->tabContainer()->captureStart('cctabs', array('class' => 'u-tab'));

$this->contentPane()->captureStart('ccdashboard', array('region' => 'center', 'style' => 'width: 100%; 
    padding: 0px; margin: 0px; border: 0px;', 'title' => 'Custom Container'));
echo $this->render($this->ccdash);
echo $this->contentPane()->captureEnd('ccdashboard');
echo $this->tabContainer()->captureEnd('cctabs');

echo $this->contentPane()->captureEnd('cclayout');
// End border container layout
echo $this->borderContainer()->captureEnd('customcontainer');
