<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_samba
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id: linkgroup.phtml 914 2008-08-25 11:31:06Z fkhan $
 * @lastchangeddate $LastChangedDate: 2008-08-25 17:31:06 +0600 (Mon, 25 Aug 2008) $
 **/
?>
<div class="note">
Activation Samba Plugin for this group. Upon activation, members of this group would be 
able to subscribe to the Samba User Plugin</div>
<br />
<div class="info">
The Samba plugin does not accept any configuration paramters
</div>

<button dojoType="dijit.form.Button"> Add Samba Plugin
    <script type="dojo/method" event="onClick">
    zivios.callAction('/samba/group/dolinktoservice',{
            dn: '<?php echo urlencode($this->dn);?>',
            srvdn: '<?php echo urlencode($this->srvdn);?>'},
            this.id);
    </script>
</button>   

