<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/

$formid   = Zivios_Util::randomString(8);
$regexLib = Zivios_Util::getRegexLibrary();
?>
<div class="heading">General configuration</div>

<div class="content">

    <form id='<?php echo $formid; ?>' enctype="application/x-www-form-urlencoded" method="post" 
        action="#" dojoType="dijit.form.Form">

    <div class="zflabel" style="width: 150px;">Application Name: </div>
    <input name="zcfggeneral[rq_alnumwithspaces_appname_Application+Name]" type="text" dojoType="dijit.form.ValidationTextBox" 
        size="16" maxlength="64" regExp="<?php echo $regexLib->exp->alnumwithspaces; ?>" required="true" 
        invalidMessage="Invalid characters in field value." class="zfgenField" 
        value="<?php echo $this->config->general->appname; ?>" />
    <div class="cboth"></div>

    <div class="zflabel" style="width: 150px;">Short Application Name: </div>
    <input name="zcfggeneral[rq_alnumnospaces_appnameshort_Short+Application+Name]" type="text" dojoType="dijit.form.ValidationTextBox" 
        size="16" maxlength="64" regExp="<?php echo $regexLib->exp->alnumnospaces; ?>" required="true" 
        invalidMessage="Invalid characters in field value." class="zfgenField" 
        value="<?php echo $this->config->general->appnameshort; ?>" />
    <div class="cboth"></div>

    <div class="zflabel" style="width: 150px;">Memcache Host: </div>
    <input name="zcfggeneral[rq_hostname_memcachehost_Memcache+Host]" type="text" dojoType="dijit.form.ValidationTextBox" 
        size="16" maxlength="64" regExp="<?php echo $regexLib->exp->hostname; ?>" required="true" 
        invalidMessage="Invalid characters in field value." class="zfgenField" 
        value="<?php echo $this->config->cache->host; ?>" />
    <div class="cboth"></div>

    <div class="zflabel" style="width: 150px;">Memcache Port: </div>
    <input dojoType="dijit.form.NumberSpinner" value="<?php echo $this->config->cache->port; ?>" smallDelta="1"
        largeDelta="10" defaultTimeout="500" timeoutChangeRate="100" maxLength="5" constraints="{min:1,max:65535,places:0}"
        name="zcfggeneral[rq_digits_memcacheport_Memcache+Port]" class="zfgenField" style="width: 230px;"/>
    <div class="cboth"></div>

    <div class="zflabel" style="width: 150px;">Cache Expire (seconds):  </div>
    <input dojoType="dijit.form.NumberSpinner" value="<?php echo $this->config->cache->expiretime; ?>" smallDelta="1"
        largeDelta="10" defaultTimeout="500" timeoutChangeRate="100" maxLength="6" constraints="{min:30,max:864000,places:0}"
        name="zcfggeneral[rq_digits_memcacheexpire_Cache+Expire]" class="zfgenField" style="width: 230px;"/>
    <div class="cboth"></div>

    <div class="zflabel" style="width: 150px;">JavaScript Debug Mode:  </div>
    <input dojoType="dijit.form.NumberSpinner" value="<?php if ($this->config->view->dojo->isDebug == true) { echo "1"; } else { echo "0"; } ?>" smallDelta="1"
        largeDelta="1" defaultTimeout="500" timeoutChangeRate="100" maxLength="1" constraints="{min:0,max:1,places:0}"
        name="zcfggeneral[rq_digits_dojodebug_JavaScript+Debug+Mode]" class="zfgenField" style="width: 230px;"/>
    <div class="cboth"></div>
    
    <div class="info infocl" style="width: 320px; margin-left: 10px; margin-top: 15px;">Changing the theme requires a rebuild of dojo. To simply test
    a theme, you can deselect the option &quot;Use Dojo Build&quot;. Please see the Zivios Wiki for detailed information.</div>

    <div class="zflabel" style="width: 150px;">Select Theme: </div>
    <select dojoType="dijit.form.FilteringSelect" name="zcfggeneral[rq_alnospaces_ziviostheme_Zivios+Theme]" class="zfgenField"
        style="margin-top: 10px; width: 230px;">
        <option value="tundra">Tundra</option>
        <option value="soria">Soria</option>
        <option value="nihilo">Nihilo</option>
        <option value="noir">Noir</option>
    </select>
    <div class="cboth"></div>

    <?php
    $ubuild = false;
    if ($this->config->view->dojo->useBuild == "yes") {
        $ubuild = true;
    }
    ?>
    <div class="zflabel" style="width: 150px;">Use Dojo Build:  </div>
    <input name="zcfggeneral[rq_alnospaces_usedojobuild_Use+Dojo+Build]" dojoType="dijit.form.CheckBox" value="yes" class="zfgenField"
    <?php if ($ubuild === true) echo 'checked'; ?> style="margin-top: 10px;"/>
    <div class="cboth"></div>

    <div class="zflabel" style="width: 150px;">&nbsp;</div>
    <input onclick="zivios.postxhr('/default/zconfig/update', '', '<?php echo $formid; ?>',
        'form', 'json', [], [], [], [], this.id); return false;" 
        name="zcfgupdate" value="Update Configuration"
        type="submit" label="Update Configuration" dojoType="dijit.form.Button"/>
    <div class="cboth"></div>
    <input type="hidden" name="zcfggeneral[rq_alnospaces_section_Update+Section]" value="general"/>
    </form>
</div>

