<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_ldap
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>

<p class="headline">Zivios Directory Service</p>
<p class="content">
Please select an option from the &quot;<b>Service Menu</b>&quot; to proceed.
</p>

<div class="note notecl" style="width: 650px; margin-left: 10px;">
The service configuration, schema management and LDAP monitor are all currently
in active development. If you would like to request a feature or report a problem,
please do so <a href="http://bugs.zivios.org" target="_new">here</a>.
</div>
