<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_openafs
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id: addservice.phtml 919 2008-08-25 11:45:23Z fkhan $
 * @lastchangeddate $LastChangedDate: 2008-08-25 17:45:23 +0600 (Mon, 25 Aug 2008) $
 **/

?>
<form id="afsplugin" method="post" action="#" onsubmit="return false;">
<table width="95%" align="center">
<tr>
	<td>AFS Cell Name</td>
	<td> : <input size="32" type="text" name="afscellname" value="" /></td>
</tr>
<tr>
	<td NOWRAP>AFS System Role</td>
	<td>
	: <input type="checkbox" value="1" name="DB" />DB Server <br />
	: <input type="checkbox" value="1" name="FS" />File Server <br />
	: <input type="checkbox" value="1" name="CL" />Client <br />
	: <input type="radio" value="1" name="doinstall" /> Install Service
	<input type="radio" value="2" name="doinstall" CHECKED /> Service Already Installed
	</td>
</tr>
<tr>
	<td colspan="3">
		<input type="submit" name="pluginaction" value="<?php echo $this->option; ?>"
			onclick="javascript:callFormUpdate('afsplugin', '/openafs/server/addService/');" />
		<input type="hidden" name="utype" value="<?php echo $this->utype; ?>" />
		<input type="hidden" name="operate_dn" value="<?php echo $this->obj->getdn(); ?>" />
		<input type="hidden" name="addRequestFor" value="service" />
	</td>
</tr>
</table>
</form>
