<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_openafs
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id: deletevolume.phtml 919 2008-08-25 11:45:23Z fkhan $
 * @lastchangeddate $LastChangedDate: 2008-08-25 17:45:23 +0600 (Mon, 25 Aug 2008) $
 **/

?>
<table border="0" width="100%" align="center">
<tr>
	<td><b>Delete Volume</b></td>
</tr>
<tr>
	<td>You are about to <b><font color="red">delete the volume</font></b>:
	<b><?php echo $this->volEntry->getProperty("cn"); ?></b>. All RO and RW mount
	points for this volume will be removed from the file system.
	<br />
	Are you absolutely certain you want to do this?
	<p><a href="#" onClick="javascript:deleteVolume();"><b>Yes, Delete this Volume</b></a></p>
	</td>
</tr>
</table>

<script language="javascript">
/**
 * Show EditMountPoint Options
 */
deleteVolume = function (voldn)
{
	var msg = "You are about to DELETE a volume permanently.";
	msg += " \n\nAre you certain you wish to continue?";

	var url = "/openafs/server/deletevolume";
	var div = "optrst";

	if (!confirm(msg))
       return false;

    var data = {voldn: '<?php echo $this->volEntry->getdn(); ?>', operate_dn: '<?php echo $this->obj->getdn(); ?>'};
	rpc = Object.toJSON(data);

	var ma = new Ajax.Updater (
		{success: div},
		url,
		{
			method: 'get',
			parameters: 'mr='+rpc,
			evalScripts: true,
			onLoading: function(request) {
				showNotify()
			},
			onComplete:function(request) {
				hideNotify()
			},
		}
	);
}
</script>