<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_openafs
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id: managerdashboard.phtml 919 2008-08-25 11:45:23Z fkhan $
 * @lastchangeddate $LastChangedDate: 2008-08-25 17:45:23 +0600 (Mon, 25 Aug 2008) $
 **/

?>
<script language="javascript">
new Ajax.Autocompleter("searchVol", "srhresult", "/openafs/server/searchVolume",
	{
		parameters: "operate_dn=<?=urlencode($this->obj->getdn())?>",
		afterUpdateElement : redirectToVol
	}
);

function redirectToVol(text, li)
{
	getVolDetails('/openafs/server/getvoldetails','pgupdate', li.id);
}
</script>

<table>
<tr>
	<td valign="top">
	<table class="plugindash" width="300">
		<th>Search for a Volume: </th>
	<tr>
		<td NOWRAP valign="top">
		<?php
		/**
		 * Autocomplete form here for searching volumes by name or ID.
		 */
		?>
		<form>
		<img src="<?php echo $this->imgBase; ?>/icons/magglass.png" />
		<input type="text" id="searchVol" name="volsearch" size=30 value="Search..." onmousedown="javascript:document.getElementById('searchVol').value='';"/>
		</form>
		</div>
		<div id="srhresult" class="autocomplete"></div>
		</td>
	</tr>
	</table>
	</td>
	<td valign="top">

	<table class="plugindash" width="300">
		<th>Partition Details</th>
	<tr>
		<td NOWRAP>
		<?php
		/**
		 * Show partition listing as well as total space, used space
		 * and obviously available space.
		 */
		?>
		</td>
	</tr>
	</table>
	</td>
</tr>
</table>
