<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_mail
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id: accountdetails.phtml 995 2008-09-02 12:11:13Z fkhan $
 * @lastchangeddate $LastChangedDate: 2008-09-02 17:11:13 +0500 (Tue, 02 Sep 2008) $
 **/
?>
<script language="JavaScript">

deleteAlias = function (alias)
{
	form = document.getElementById('removealias');
	form.aliastodelete.value = alias;
    form.action.value = 'delete';
	callAjaxRender('removealias','/mail/user/deletealias','innermailuser');
}
</script>
<div id="pgupdate">
	<div style="padding-left: 10px;">

		<div style="width: 140px;" class="floatleft">e-Mail Address</div>
		<div style="width: 350px;" class="floatleft">
			<?php echo $this->dashboardData['email']; ?>
		</div>
		<div class="clear"></div>

		<form id="removealias" method="post" action="#">
		<input type="hidden" name="operate_dn" value="<?php echo $this->obj->getdn(); ?>" />
		<input type="hidden" name="aliastodelete" value=""/>
		</form>

		<div style="width: 140px;" class="floatleft">e-Mail Aliases</div>

		<?php
		$firstalias=1;
		if (sizeof($this->dashboardData['aliases']) == 0) {
		?>
				<em>None defined</em>
		<?php
		} else {
			$aliases = $this->dashboardData['aliases'];
			foreach ($aliases as $alias) {
				if (!$firstalias) {
					?>
					<div style="width: 140px;" class="floatleft"></div>
					<?php
				} else
					$firstalias = 0;
				?>
				<div style="width: 350px;" class="floatleft">
				<?php echo $alias;?>  [ <a href="#" onclick="javascript:deleteAlias('<?php echo $alias;?>');">delete</a> ]
				</div>
				<div class="clear"></div>
				<?php

				}

			}
			?>
		<br />
		<form id="addalias" method="post" action="#" onsubmit="return false;" style="padding-left:0px; width: 498px;">
		<fieldset>
		<legend>Add an Alias</legend>
		<label for="Add Alias">e-Mail Alias: </label>
			<input type="text" name="newalias" value="" maxlength="32" size="20"> @
			<select name="aliasdomain">
			<?php
			foreach ($this->dashboardData['maildomains'] as $maildomain) {
				?>
				<option value='<?php echo $maildomain;?>'><?php echo $maildomain;?></option>
				<?php
			}
			?>

			</select>
			<input type="hidden" name="operate_dn" value="<?php echo $this->obj->getdn(); ?>" />
			<input type="submit" name="aalias" value="Add Alias"
				onclick="javascript:callAjaxRender('addalias','/mail/user/addalias','innermailuser'); return false;"/>
		</fieldset>
		</form>

		<form id="chgquota" method="post" action="#" onsubmit="return false;" style="padding-left:0px; width: 498px;">
		<fieldset>
		<legend>Update User Quota</legend>
		<label for="Add Alias">e-Mail Quota: </label>
			<input type="text" name="nquota" value="<?php
			echo $this->dashboardData['quota'];?>" maxlength="6" size="28"> MB
			<input type="submit" name="uquota" value="Update Quota"
				onclick="javascript:callAjaxRender('chgquota','/mail/user/updateMboxQuota','innermailuser'); return false;" />
		</fieldset>

		<input type="hidden" name="operate_dn" value="<?php echo $this->obj->getdn(); ?>" />
		</form>


	</div>
</div>
