<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_mail
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id: folders.phtml 914 2008-08-25 11:31:06Z fkhan $
 * @lastchangeddate $LastChangedDate: 2008-08-25 17:31:06 +0600 (Mon, 25 Aug 2008) $
 **/

?>
<div id="pgupdate">
	<div style="padding-left: 10px;">
	<?php
	foreach ($this->dashboardData['mailboxes'] as $mbox) {
        $name = explode('.',$mbox);
        $name = $name[sizeof($name)-1];
		echo '
		<div style="width: 140px;" class="floatleft">'.$name.'</div>
		<div style="width: 350px;" class="floatleft">'.$mbox.'</div>
		<div class="clear"></div>
		';
	}
	?>
	</div>
</div>

