<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_mail
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id: unsubscribe.phtml 914 2008-08-25 11:31:06Z fkhan $
 * @lastchangeddate $LastChangedDate: 2008-08-25 17:31:06 +0600 (Mon, 25 Aug 2008) $
 **/

?>

	<div style="padding-left: 10px;">
	<div class="warn" style="width: 450px;">
	<form id="unsubmbox" method="post" action="#" onsubmit="return false;" width="400">
    <input type="hidden" name="action" value="delete" />
	<input type="hidden" name="operate_dn" value="<?php echo $this->obj->getdn(); ?>" />
	You are about to unsubscribe this user from his mailbox. This action will delete all
	messages a user may be storing in his mailbox as well as disable all mail services for the user.
	<p style="font-weight: bold; text-align: center;">
	Are you absolutely certain you want to continue? <br /><br />
	<input type="submit" onclick="javascript:callFormUpdate('unsubmbox','/mail/user/delete');" value="Yes, remove mailbox">
	</p>
	</form>
	</div>
	</div>

