<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
?>
<div class="info"  style="width: 92%; margin-left: 10px;">
You are about to add a Branch Office. This allows the further provisioning of User, Group and Computer Containers.
</div>
<br />
<div style="float: left; width: 40%;">
<?php
echo $this->form;
?>
</div>
<div style="float: left; width: 59%">
    <div class="note">
        <ul>
            <li>Branch name can contain alphabets characters and spaces only</li>
            <li>Phone and Fax fields format is as follows. <br /> xxxxxxxxxx or xxx-xxx-xxxx</li>
        </ul>
    </div>
</div>
<div style="clear: both;"></div>