<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
Zend_Dojo_View_Helper_Dojo::setUseDeclarative();
?>
<p class="toolbar">
<div id="ltoolbar01" dojoType="dijit.Toolbar" style="width:30%; height: 23px; float: left;">
    <button dojoType="dijit.form.Button" id="addaci">Add Ldap ACI
        <script type="dojo/method" event="onClick">
        form = dijit.byId('aclform');
        form.href='/acl/renderform/type/aci/dn/<?php echo urlencode($this->entry->getdn());?>';
        form.refresh();
        </script>
    </button>
    <button dojoType="dijit.form.Button" id="addzvacl">Add Zivios Acl
        <script type="dojo/method" event="onClick">
        form = dijit.byId('aclform');
        form.href='/acl/renderform/type/emsacl/dn/<?php echo urlencode($this->entry->getdn());?>';
        form.refresh();
        </script>
    </button>
</div>
<div id="ltoolbar02" dojoType="dijit.Toolbar" style="width:70%; height: 23px; float: left; text-align: right;">
<B><?php echo $this->entry->getProperty("cn"); ?></b> | dn: <?php echo $this->entry->getdn();?> &nbsp;&nbsp;
</div>
</p>
