<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/

echo $this->doctype() . "\n";
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php

    echo $this->headTitle();
    echo $this->headMeta();
    echo $this->headLink(array(
        'rel' => 'icon',
        'href' => 'public/imgs/favicon.ico',
        'type' => 'image/x-icon'));
    ?>
    <noscript>
        <meta http-equiv="refresh" content="0; url=/public/jsdisabled.html"/>
    </noscript>

    <style type="text/css">
    <!--
    <?php echo $this->css . "\n"; ?>
    -->
    </style>

</head>
<body class="<?php echo $this->zvtheme; ?>">

<div id="preloader" style="display: block;">Loading, please wait...</div>

<div id="zvPrimaryContainer" style="display: none; width: 100%; height: 100%;">
    <div dojoType="dijit.layout.BorderContainer" design="headline" gutters="false" liveSplitters="false" id="layout">
        <?php
            echo $this->render('_header.phtml');
            echo $this->render('_body.phtml');
        ?>
    </div>
</div>
</body>
<?php echo $this->dojo()->enable() . "\n"; ?>
</html>

