<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
if (!is_array($this->compatComps)) {
    $requiredOs = rtrim($this->compatComps, ',');
}
if (!isset($requiredOs)) {
    // Supported Linux distributions were detected.
    ?>
    <div class="floatleft" style="width: 340px;">
        <p class="headline">Adding the Squid Service to Zivios</p>
        <?php
        // squid add service to group form.
        echo $this->form;
        ?>
    </div>

    <div class="floatleft" style="width: 400px; margin-top: 40px;">
        <div class="info infocl" style="margin-bottom: 20px;">
        You are about to add the Squid (Internet Proxy) service to Zivios. Please ensure that
        Squid has been configured on the remote system as per Zivios documentation.<br /><br />
        The installation process will ensure the Squid service is running (on the remote server)
        before adding it to Zivios.
        </div>
        <div class="note notecl">
        It is recommended that <b>service labels</b> be kept unique for easier identification during group
        service subscription. Once defined, service labels cannot (currently) be changed via Zivios.
        </div>
    </div>
    <div class="clearboth"></div>
 <?php
 } else {
    // No supported Linux distributions detected.
    ?>
    <div class="alert">
    No compatible systems were found for the Zivios Squid service. A listing of
    compatible operating systems is shown below: 
    <ul>
        <?php
        $supportedSys = explode(',', $requiredOs);
        foreach ($supportedSys as $system) {
            $sysDetails = explode('-', $system);
            echo '<li/>'.ucfirst(strtolower($sysDetails[0])) . ' ' . 
                ucfirst(strtolower($sysDetails[1]));
        }
        ?>
    </ul>
    </div>
    <?php
}
