<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_ca
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
?>
<div id="pgupdate">
	<div style="padding-left: 10px;">
	<p>
	<div class="info" style="width: 450px;">Certificate capabilities extend certain
	privileges to the User. However, giving Code Signing capabilities to a user who
	simply needs E-Mail protection is not recommended.</div>
	</p>
	<form id="gencert" method="post" action="#" onsubmit="return false;"
		style="padding-left: 10px; width: 495px;">
	<fieldset>
	<legend>Select Certificate Capabilities</legend>

	<label for="clwc"></label>
		<input type="checkbox" name="cct" value="https-client" /> Web Client (TLS) <br />
	<label for="clep"></label>
		<input type="checkbox" name="cct" value="smime" onclick="vfdisplay('emailaddrs');" /> Email Protection (S/MIME)<br />

	<!-- Option display for Email Protection -->
	<div id="emailaddrs" style="display: none; padding: 5px; background-color: #f1f1f1;"">
		<label for="emhelp"></label>
			Enter e-mail addresses to protect
		<label for="em"></label>
			<input type="text" value="" name="emailaddrs" size="22" maxlength="64" /> <br />
		<label for="em"></label>
			<input type="text" value="" name="emailaddrs" size="22" maxlength="64" /> <br />
	</div>

	<label for="clpki"></label>
		<input type="checkbox" name="cct" value="pkinit-client"
		onclick="vfdisplay('pkinit');" /> PK-INIT (Smart card Logins) <br />

	<!-- Option display for pkinit -->
	<div id="pkinit" style="display: none; padding: 5px; background-color: #f1f1f1;">
		<label for="pki-info"></label>
			Detected PKInit ID: <br />
		<label for="pki-info"></label>
			<input name="pksandisplay" disabled type="text"
				value="<?php echo $this->obj->getProperty("krb5principalname"); ?>" size="22" maxlength="64" /> <br />
	</div>

	<input type="submit" value="Generate Certificate"
		onclick="javascript:callFormUpdate('gencert', '/ca/user/activatePlugin/');" />
	</fieldset>
	<input type="hidden" name="operate_dn" value="<?php echo $this->obj->getdn();?>" />
	<input type="hidden" name="pksan" value="<?php echo $this->obj->getProperty("krb5principalname"); ?>" />
	<input type="hidden" name="action" value="activate" />
	</form>
	</div>
</div>

<script language="javascript">
vfdisplay = function(divid)
{
	$(divid).toggle();
}
</script>
