<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_ca  
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<style>
.popupWindow {
    background: #fafafa;
    width:95%;
    height:95%;
    border: 1px dotted #ccc;
    font-family: "verdana, sans-serif, arial";
    font-size: 11px;
    padding: 10px;
    overflow: auto;
}

.closePopup {
    border-bottom: 1px solid #ccc;
    width: 100%;
    line-height: 18px;
    text-align: right;
}
</style>

<div class="popupWindow">
    <div class="closePopup">
    <a href="#" onClick="javascript:self.close(); return false;">Close Window</a></div>
    Copy and Paste the Certificate as required.
    <hr width=1>
    <b>Certificate Public Key:</b>
    <p style="background-color: #f1f1f1; font-size: 9px; font-face: verdana; width: 500px; padding: 0px; margin: 0px;">
    <?php echo nl2br($this->certDetails['pubcert']); ?>
    </p>

    <b>Certificate Private Key:</b>
    <p style="background-color: #f1f1f1; font-size: 9px; font-face: verdana; width: 500px; padding: 0px; margin: 0px;">
    <?php echo nl2br($this->certDetails['prvkey']); ?>
    </p>
</div>

