<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_ca
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<div id="pgupdate">
    <div style="padding-left: 10px;">
    <div class="info" style="width: 450px;">
    Certificate download is currently available only in PEM format.
    </div>
    <br />
    <a href="#" onclick="javascript:openWindow('/ca/user/downloadcertwin/?operate_dn=<?php
    echo urlencode($this->obj->getdn());?>', 'downloadcertwin'); return false;">Download Certificate</a>
</div>
