<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

// Border container for server entry view.
$this->borderContainer()->captureStart('viewserverentry', array(
    'design' => 'headline', 
    'style' => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

    // Server Entry toolbar
    $this->contentPane()->captureStart('serverentrytb01', array(
        'region' => 'top', 
        'style' => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));
    echo $this->render($this->toolbar);
    echo $this->contentPane()->captureEnd('serverentrytb01');

    // Content pane for tab container.
    $this->contentPane()->captureStart('serverentrytabc', array(
        'region' => 'center',
        'style' =>'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

    // Tab container and primary dashboard tab.
    $this->tabContainer()->captureStart('serverentrytabs', array('class' => 'u-tab'));
    $this->contentPane()->captureStart('serverentrydashboard', array(
        'region' => 'center',
        'style' => 'width: 100%; padding: 0px; margin: 0px; border: 0px;',
        'title' => $this->tabheading));
    
    echo $this->render($this->dataview);
    echo $this->contentPane()->captureEnd('serverentrydashboard');

    // Tab capture end and display.
    echo $this->tabContainer()->captureEnd('serverentrytabs');

    // Tab container capture end and display.
    echo $this->contentPane()->captureEnd('serverentrytabc');

// Border container capture end and display.
echo $this->borderContainer()->captureEnd('viewserverentry');
