<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

Zend_Dojo_View_Helper_Dojo::setUseDeclarative();
$this->dojo()->enable();

// start border layout container for locality entry.
$this->borderContainer()->captureStart('viewserverlocalityentry', array('design' => 'headline', 
    'style' => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

// Content pane for locality toolbar
$this->contentPane()->captureStart('ltb01', array('region' => 'top', 'style' => 'width: 100%; 
    padding: 0px; margin: 0px; border: 0px;'));
if ($this->toolbar)
    echo $this->render($this->toolbar);
echo $this->contentPane()->captureEnd('ltb01');
// Content pane for Zivios locality toolbar ends above.

$this->contentPane()->captureStart('localitydata', array('region' => 'center', 'style' =>'width: 100%; padding: 0px; margin: 0px; border: 0px;'));
$this->tabContainer()->captureStart('localitytabs', array('class' => 'u-tab'));

$this->contentPane()->captureStart('localityfirst', array('region' => 'center', 'style' => 'width: 100%; 
    padding: 0px; margin: 0px; border: 0px;', 'title' => $this->tabheading));
echo $this->render($this->dataview);
echo $this->contentPane()->captureEnd('localityfirst');

echo $this->tabContainer()->captureEnd('localitytabs');

echo $this->contentPane()->captureEnd('localitydata');
// End border container layout
echo $this->borderContainer()->captureEnd('viewserverlocalityentry');