<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_ntp
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
 
$this->borderContainer()->captureStart('ntpmain', array('design' => 'sidebar', 'style' => 
    'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

$this->contentPane()->captureStart('ntpgeneral', array('region' => 'left', 
    'style' => 'width: 350px; padding: 0px; margin: 0px; border-left: 0px; border-top: 0px; border-bottom: 0px;',
     'href' => '/ntp/service/ntpgeneral/dn/'.urlencode($this->service->getdn())));


echo $this->contentPane()->captureEnd('ntpgeneral');

$this->contentPane()->captureStart('ntpright', array('region' => 'center', 
    'style' => 'padding: 0px; margin: 0px; border-left: 0px; border-top: 0px; border-bottom: 0px;'));
    
$this->borderContainer()->captureStart('ntpserverssection', array('design' => 'headline', 
    'style' => 'width: 99%; padding: 0px; margin: 0px; border: 0px; '));

/*
* NTP Servers BC
*/
 
$this->contentPane()->captureStart('ntpserversdisplay', array('region' => 'top', 'style' => 'padding: 0px; 
    margin: 0px; border: 0px; border-top: 0px; height: 200px;',
                     'href' => '/ntp/service/serversdisplay/dn/'.urlencode($this->service->getdn())));


echo $this->contentPane()->captureEnd('ntpserversdisplay');

$this->contentPane()->captureStart('ntpserverform', array('region' => 'center', 'style' => 'padding: 0px; 
                          margin: 0px; border-left: 0px; border-right: 0px; border-top: 0px; height: 100px;'));
                          
echo $this->render('service/dashboard/serverform.phtml');

echo $this->contentPane()->captureEnd('ntpserverform');

$this->contentPane()->captureStart('ntpsyncstatus', array('region' => 'bottom', 'style' => 'padding: 0px; 
                        margin: 0px; border-left: 0px; border-right: 0px; border-top: 0px; height: 200px;',
                        'href' => '/ntp/service/syncstatus/dn/'.urlencode($this->service->getdn())));

echo $this->contentPane()->captureEnd('ntpsyncstatus');

echo $this->borderContainer()->captureEnd('ntpserverssection');

echo $this->contentPane()->captureEnd('ntpright');

echo $this->borderContainer()->captureEnd('ntpmain');
