<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
$regex = Zivios_Regex::loadLibrary();
?>
<div class="note"> You can add a new server as sync source below </div>

<form action="#" method="post" id="addsrvform" dojoType="dijit.form.Form" onsubmit="return false;">
    <input type="hidden" name="dn" value="<?php echo $this->service->getdn();?>"/>
    <input type="hidden" name="changeaction" value="add"/>
    
    <div style="padding-left: 5px; width:70%; float: left;">
    <Label for="acl"><B>New Sync Source:  </b> </label>
        <input type="text" dojoType="dijit.form.ValidationTextBox" name="srv" id="srv" 
        regExp="<?php echo $regex->exp->hostname;?>" required="true" invalidMessage="Invalid Hostname">
    </div>
    
    <div style="width: 26%; float: left;">
    <?php 
    if (!$this->service->pingZiviosAgent()) 
        $disabled="disabled='true'";
    else
        $disabled ="";
    ?>
    <button id="addsrvform-submit" dojoType="dijit.form.Button" label="Add Sync Source" <?php echo $disabled;?>>
        <script type="dojo/method" event="onClick"> 
            zivios.formXhrPost('addsrvform', '/ntp/service/dochangesrv');
        </script>
    </button>   
    </div>
    <div style="clear: both;"></div>
</form>
