<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_dns
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
$strpCn  = strtolower(preg_replace("/[^a-z0-9]/i", "", $this->zone->getProperty('cn')));
$cpId = $strpCn . '-dnszeopts';
$tbId = $strpCn . '-toolbar';
?>
<div id="<?php echo $tbId; ?>" style="width: 360px !important;" dojoType="dijit.layout.ContentPane">
<p class="toolbar">
<div dojoType="dijit.Toolbar">
    <div dojoType="dijit.form.DropDownButton">
        <span><b>Zone Menu</b></span>
        <ul dojoType="dijit.Menu">
        <li dojoType="dijit.MenuItem" label="Delete Zone" iconClass="genericIcon deleteIcon" event="onclick">
            <script type="dojo/method" event="onClick">
                zivios.cpaneRefresh(
                '<?php echo $cpId; ?>', // cpane target
                '/dns/service/deletezone/zonedn/<?php echo urlencode($this->zone->getdn()); ?>/dn/<?php echo urlencode($this->service->getdn());?>'
                );
            </script>
        </li>
        </ul>
    </div>
</div>
</p>
</div>
<?php
// Echo zone record pull options form.
echo $this->optForm;
?>
<div id="<?php echo $cpId; ?>" style="width: 360px !important; margin: 0px auto;"
    dojoType="dijit.layout.ContentPane" 
    href="/dns/service/getrecordentryform/dn/<?php echo urlencode($this->service->getdn());?>">
</div>
