<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
Zend_Dojo_View_Helper_Dojo::setUseDeclarative();
?>
<p class="toolbar">
<div id="ltoolbar01" dojoType="dijit.Toolbar" style="width:30%; height: 23px; float: left;">
    <div dojoType="dijit.form.DropDownButton">
        <span><b>Desktop Container Menu</b></span>
        <ul dojoType="dijit.Menu" id="containermenu">
                <li dojoType="dijit.MenuItem" label="Delete Desktop Container"
                    onclick="javascript:zivios.loadApp('/server/deletecontainer/dn/<?php echo $this->entry->getdn(); ?>',
                        'localitytabs','deleteContainer','Delete Desktop Container')"></li>
        </ul>
    </div>
</div>
<div id="ltoolbar02" dojoType="dijit.Toolbar" style="width:70%; height: 23px; float: left; text-align: right;">
    <?php echo $this->entry->getProperty("cn"); ?> &nbsp;&nbsp;
</div>
</p>
