<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_samba
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id$
 * @lastchangeddate $LastChangedDate$
 **/
?>

<div id="pgupdate">
<br />

<b>Initializing Samba Plugin</b>

<form id="addplugin" onsubmit="javascript:return false;">
<input type="hidden" name="operate_dn" value="<?php echo $this->obj->getdn();?>" />
<input type="hidden" name="action" value="install" />
<fieldset>
<legend>Add Samba Plugin</legend>
<br />
<label>Home Drive</label>
<input type="text" size="32" name="homedrive"/>

<br />
<label>User Changeable Password</label>
<input type="checkbox" name="pwdcanchage" value="1" />

<br />
<label>Force Password Change on Next Login</label>
<input type="checkbox" name="pwdmustchage" value="1" />

<br />
<label>Profile Path</label>
<input type="text" size="32" name="profilepath"/>

<br />
<label>Home Drive</label>
<input type="text" size="32" />
</fieldset>
<br />
<fieldset>
<legend>Samba Server Share Access</legend>
TODO: Display Share Access Info
</fieldset>
<br />
<input type="submit" value="Apply" onclick="javascript:callAjaxRender('addplugin','/samba/user/addplugin','pgupdate');"/>
</form>
</div>



