<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

Zend_Dojo_View_Helper_Dojo::setUseDeclarative();
$this->dojo()->enable();

$this->borderContainer()->captureStart('sambauserentry', array(
    'design' => 'headline',
    'style' => 'width: 100%; padding: 0px; margin: 0px;'));

    $this->contentPane()->captureStart('sambausercptop', array(
        'region' => 'top', 
        'style' => 'width: 99.8%;padding: 0px; margin: 0px; height: 23px;'));
    echo $this->render('user/toolbar.phtml');
    echo $this->contentPane()->captureEnd('sambausercptop');

    $this->contentPane()->captureStart('sambausercpcenter', array(
        'region' => 'center',
        'style' => 'width: 99.8%; padding: 0px; margin: 0px;', 
        'refreshOnShow' => 'false',
        'href' => '/samba/user/config/dn/'.urlencode($this->user->getdn())));
echo $this->contentPane()->captureEnd('sambausercpcenter');

echo $this->borderContainer()->captureEnd('sambauserentry');

