<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<p class="headline">Remove Samba Plugin from User</p>

<div class="alert alertcl" style="margin-left: 10px; width: 500px;">
You are about to <b>remove</b> the Zivios Samba plugin from this User. All user mailboxes and mail data would
be permanently destroyed. If you wish to disable this user's email you can do so without removing the mailbox
<br /><br />
<b>Are you certain you wish to proceed?</b>
</div>

<div style="margin-left: 10px; margin-top: 5px;">
    <button dojoType="dijit.form.Button" >Yes, Remove Samba Plugin
        <script type="dojo/method" event="onClick">
            zivios.callAction('/samba/user/dodelete', {
                dn: '<?php echo urlencode($this->user->getdn());?>'},this.id);
        </script>
    </button>
</div>
