<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
 
$formid   = Zivios_Util::randomString(8);

?>
<div class="note">

<P class="heading">
Mass Subscribe All Users Under <B><?php echo $this->ou->getdn();?></b>
</P>
</div>
<div class="cboth"></div>
<div class="zflabel" style="width: 150px;">Add To Group (Search):</div>
 <form id='<?php echo $formid; ?>' enctype="application/x-www-form-urlencoded" method="post" 
            action="#" dojoType="dijit.form.Form">
            
<div dojotype="zivios.AutocompleteReadStore" jsid="dogroupsearch" 
    url="/default/group/getallgroups/dn/<?php echo urlencode($this->ou->getdn()); ?>/" 
    requestmethod="get"></div>

<input dojoType="dijit.form.FilteringSelect" class="zfgenField" required="true"
    store="dogroupsearch" name="addtogroup[rq_dn_agsearch_Group+Name_enc]" hasDownArrow="false" 
    />
    
<input type="hidden" name="oudn" value="<?php echo $this->ou->getdn();?>" />

<div class="cboth">
<br />
<div class="zflabel" style="width: 100px;">&nbsp;</div>
        <input onclick="zivios.postxhr('/default/group/dosubscribeou', '', '<?php echo $formid; ?>',
            'form', 'json', [], [], [], [], this.id); return false;" 
            name="zvsubou" value="Subscribe OU Users To Group" 
            type="submit" label="Subscribe OU Users to Group" dojoType="dijit.form.Button"/>
        <div class="cboth"></div>
<br />
The following users would be subscribed to this group:
<br />
<br />
<?php
$count = 1;
foreach($this->users as $user) {
    ?>
    
    <div style="float:left; width: 150px; height: 25px;"><?php echo $user->getProperty('cn');?></div>
    <?php
    if ($count % 3 == 0) {
        ?>
        <div class="cboth"></div>
        <?php
    }
    $count++;
}
?>
    
