<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<h3><font color="green">Welcome</font> <?php echo $this->user->getProperty('cn');?>.</h3>
<div style="font-size: 12px;">
    Welcome to the <b>Zivios Enterprise Management System</b>. Before you begin administering
    your systems with Zivios, please be sure to visit the <a href="http://wiki.zivios.org">Zivios wiki</a>.
    <br/><br/>
    Some quick wiki links are provided below:
    <ul>
        <li /> <a href="http://wiki.zivios.org/wiki/First_Steps_With_Zivios" target="_blank">First Steps with Zivios</a>
        <li /> <a href="http://wiki.zivios.org/wiki/Zivios_Dns_Service" target="_blank">Administering Zivios DNS Service</a>
        <li /> <a href="http://wiki.zivios.org/wiki/Setup_Zivios_Email" target="_blank">Setting up Zivios Email Service</a>
        <li /> <a href="http://wiki.zivios.org/wiki/Setup_Zivios_Samba" target="_blank">Setting up Zivios Samba Service</a>
        <li /> <a href="http://wiki.zivios.org/wiki/Setup_Zivios_Asterisk" target="_blank">Setting up Zivios Asterisk Service</a>
        <li /> <a href="http://wiki.zivios.org/wiki/Setup_Zivios_Squid" target="_blank">Setting up Zivios Squid Service</a>
    </ul>

    <div class="info">
        <b>Need Help?</b> The Zivios community is quite active on our mailing lists. Please consider subscribing to:
        <ul>
            <li /> <a href="http://lists.zivios.org/listinfo/zivios-announce" target="_new">Zivios announce</a> -- Release announcements.
            <li /> <a href="http://lists.zivios.org/listinfo/zivios-discuss" target="_new">Zivios discuss</a> -- A User discussion list. 
        </ul>
        Zivios is currently <b>beta</b> software. We are working hard to implement additional functionality and fix issues, however,
        we do need help identifying problems. Please submit <b>bug reports</b> via the <a href="https://bugs.launchpad.net/zivios" target="_new"><b>Launchpad System</b></a>. 
    </div>
</div>

