<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_openldap
 * @copyright   Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/

$selectId = Zivios_Util::randomString(6);
?>
<div class="heading">Zivios Directory Service Replica Listing</div>
<div class="content">
Please select a Zivios Directory Service Replica for management. 
<br /><br />
<select dojoType="dijit.form.FilteringSelect" name="replicaListing" id="<?php echo $selectId; ?>">
    <?php
    $c = 0;
    foreach ($this->replicas as $replica) {
        if ($c == 0) {
            $s = 'SELECTED';
            $c++;
        } else {
            $s = '';
        }

        echo '<option value="'.urlencode($replica[1]).'" '.$s.'>'.$replica[0].'</option>';
    }
    ?>
</select>

<button dojoType="dijit.form.Button" type="button">
    Manage Replica

    <script type="dojo/method" event="onClick" args="evt">

        var jsonData = {
            'serviceDn': '<?php echo urlencode($this->service->getdn());?>',
            'replicaDn': dijit.byId('<?php echo $selectId; ?>').value,
        }

        zivios.postxhr('/openldap/service/managereplica','ldapreplicas', jsonData,
                       'json_encoded','text',[],[],[],[],this.id);
    </script>
</button>
</div>

