<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_ntp
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id: dashboard.phtml 915 2008-08-25 11:32:48Z fkhan $
 * @lastchangeddate $LastChangedDate: 2008-08-25 17:32:48 +0600 (Mon, 25 Aug 2008) $
 **/

?>
<br />
<ul id="pluginnavmenu" style="padding-left: 10px;">
	<li><a href="#" onclick="javascript:callAction('/ntp/computer/dashview/', 'ntppgupdate','<?php
		echo $this->obj->getdn(); ?>');">Dashboard</a></li>
	<li><a href="#" onclick="javascript:callAction('/ntp/computer/serviceconfig/','ntppgupdate','<?php
		echo $this->obj->getdn(); ?>');">Service Configuration</a></li>
</ul>
<br />

<?php echo $this->render("computer/dashview.phtml"); ?>
<script language="javascript">
serviceAction = function(act, dn)
{
	switch (act) {
		case "start":
		var call = '/ntp/computer/startservice';
		break;

		case "stop":
		var call = '/ntp/computer/stopservice';
		break;
	}

	var div = 'ntppgupdate';
    var data = {operate_dn: "<?php echo $this->obj->getdn(); ?>"};
	rpc = Object.toJSON(data);

	var ma = new Ajax.Updater (
	 	{success: div},
		call,
		{
			method: 'get',
			parameters: 'mr='+escape(rpc),
			evalScripts: true,
			onLoading: function(request) {
				showNotify()
			},
			onComplete: function(request) {
				hideNotify()
			},
		}
	);
}

updateClientConfig = function()
{
	var call = '/ntp/computer/updateConfig';
	var div = 'ndiv';
	var data = {operate_dn: "<?php echo $this->obj->getdn(); ?>"};
	rpc = Object.toJSON(data);

	var ma = new Ajax.Updater (
	 	{success: div},
		call,
		{
			method: 'get',
			parameters: 'mr='+escape(rpc),
			evalScripts: true,
			onLoading: function(request) {
				showNotify(),
				Element.hide('upclconf'),
				Element.show('upclprg')
			},
			onComplete: function(request) {
				hideNotify(),
				Element.hide('upclprg'),
				Element.show('upclconf')

			},
		}
	);
}
</script>