<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id: linkgroup.phtml 1122 2008-09-10 18:04:56Z gmustafa $
 **/

?>
<form id="addplugin" method="post" action="#" onsubmit="return false;" width="400">


<fieldset>
	<legend>Zivios Asterisk Group Plugin</legend>	
	<div class="notice" style="width: 74%; margin-left: 10px">
	Zivios Asterisk Group Plugin will allow group subscribers to add the Zivios Asterisk plugin enabling them to configure group level settings.

	</div>
	<input type=hidden name="srvSelect" value="<?=$this->srvSelect;?>" />
     <input type=hidden name="operate_dn" value="<?=$this->obj->getdn(); ?>" />
     <input type=hidden name="action" value="doinstall" />
     <input type="submit" value="Add" name="submit" onclick="javascript:callFormUpdate('addplugin','/asterisk/group/linkgrouptoservice');"><br />
        
</fieldset>
</form>

