<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
$formid   = Zivios_Util::randomString(8);
$regexLib = Zivios_Util::getRegexLibrary();
?>
<div class="heading">Add Trusted Network:</div>
<div class="content">
    <div class="info infocl" style="width: 350px;">
    Enter IP network below. e.g. 172.16.100.0/24 or 192.16.0.0/16
    </div>
    <form id='<?php echo $formid; ?>' enctype="application/x-www-form-urlencoded" method="post" 
        action="#" dojoType="dijit.form.Form">

    <div class="zflabel" style="width: 100px;">Trusted Network: </div>
    <input name="squidtrustednetworks[rq_ipnetwork_emssquidtrustednetworks_Trusted+Network]" type="text" dojoType="dijit.form.ValidationTextBox" 
        size="16" maxlength="64" regExp="<?php echo $regexLib->exp->ipnetwork; ?>" required="true" 
        invalidMessage="Invalid characters in form field" class="zfgenField" 
        value="" />
    <div class="cboth"></div>

    <div class="zflabel" style="width: 100px;">&nbsp;</div>
    <input onclick="zivios.postxhr('/squid/service/addtrustednetwork', '', '<?php echo $formid; ?>',
        'form', 'json', [], [], [], [], this.id); return false;" 
        name="zvaddgcontainer" value="Add Trusted Network" 
        type="submit" label="Add Trusted Network" dojoType="dijit.form.Button"/>
    <div class="cboth"></div>

    <input type="hidden" name="squidtrustednetworks[rq_dn_dn_Distinguished+Name_enc]" value="<?php echo urlencode($this->service->getdn()); ?>"/>
    </form>
</div>

