<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
?>
<div style="float: left; width: 50%; border-right: 1px solid #ccc;">
<p class="headline">Adding Group</p>
<?php
echo $this->form;
?>
</div>
<div style="float: left; width: 49%;">

<div class="info" style="margin-left: 5px; margin-right: 5px;">
<ul>
<li>Adds a normal System group</li>
<li>Posix, Kerberos, Ldap and CA plugins are automatically added enabling you to create users with those plugins</li>
<li>Next Step: Add users to this group and extend their functionality with plugins</li>
</ul>
</div>
</div>
<div style="clear: both;"></div>
