<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

 if (sizeof($this->blacklists) == 0) {
     ?>
     <div class="info"> No Emails are currently Blacklisted </div>
     <?php 
 } else {
     ?>
     <div class="note">The following table displays current blacklisted emails</div>
     <table class="general">
     <th style="text-align: left;width: 90%;">BlackListed email</th><th>Action</th>
     <?php
     $i=0;
     foreach ($this->blacklists as $bl) {
         $i++;
         ?>
         <tr>
            <td style="text-align: left;"><?php echo $bl;?></td>
            <td><button dojoType="dijit.form.Button">  delete 
                <script type="dojo/method" event="onClick">
                zivios.callAction('/mail/user/dochangebl',{
                    dn: '<?php echo urlencode($this->user->getdn());?>',
                    changeaction: 'remove',
                    alias: '<?php echo $alias;?>'},this.id);
                </script>
            </td>
        </tr>
     <?php
     }
     ?>
     </table>
     <?php
 }
 
