<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<p class="toolbar">
<div id="mail.userPlugin" dojoType="dijit.Toolbar" style="width:100%;height:23px;float:left;">
     <div id="mail.userPlugin.config" dojoType="dijit.form.Button" iconClass="genericIcon configIcon"
        showLabel="false" 
        onClick="zivios.cpaneAction('mailusercpcenter','/mail/user/config/dn/<?php
            echo urlencode($this->user->getDn()); ?>','','mail.userPlugin.config');">Plugin Configuration</div>

     <div id="mail.userPlugin.reports" dojoType="dijit.form.Button" iconClass="genericIcon reportIcon"
        showLabel="false" 
        onClick="zivios.cpaneAction('mailusercpcenter','/mail/user/reports/dn/<?php 
            echo urlencode($this->user->getDn()); ?>','','mail.userPlugin.reports');">Reports</div>

     <div id="mail.userPlugin.svcmems" dojoType="dijit.form.Button" iconClass="treeIcon treeGroupContainerIcon"
        showLabel="false" 
        onClick="zivios.cpaneAction('mailusercpcenter','/mail/user/activatemembers/dn/<?php 
            echo urlencode($this->user->getDn()); ?>','','mail.userPlugin.svcmems');">Activate Members</div>

    <span dojoType="dijit.ToolbarSeparator"></span>

    <div id="mail.userPlugin.delete" dojoType="dijit.form.Button" iconClass="genericIcon deleteIcon"
        showLabel="false" 
        onClick="zivios.cpaneAction('mailusercpcenter','/mail/user/delete/dn/<?php 
            echo urlencode($this->user->getDn()); ?>','','mail.userPlugin.delete');">Remove Plugin</div>
</div>
</p>
