<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_ca
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<div class="info" style="width: 85%; margin:20px; margin-top: 0px;">
<b>Please Note</b>: The service on the client will be restarted upon
configuration update</div>
<div id="upclconf" style="padding-left: 20px;">
[<a href="#" onclick="javascript:updateClientConfig();
    return false;"><b>Poll Master for Config &amp; Restart Service</b></a>]
</div>

<div id="upclprg" style="display: none; padding-left: 20px;">
<b>Updating client configuration from Master, please wait...</b>
</div>
