<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<div class="note notecl" style="width: 450px;">
    <b>Bulk Password Update</b> allows you to upload a space delimited list of UID PASS pairs to set initial passwords.
</div>

<P><b>UID PASS File Upload</b></p>
<form id="csvimport" enctype="multipart/form-data" action="/password/dobulkupdate" method="POST">
<fieldset>
<input type="hidden" name="MAX_FILE_SIZE" value="100000" />
<labeL>Choose a file to upload: </label> <input name="uploadedfile" type="file"/>
<br />


<div style="clear: both;"></div>
 <div class="note"><button dojoType="dijit.form.Button" id="csvimport-submit"> Start Bulk Password Update
        <script type="dojo/method" event="onClick">
        zivios.ioIframeGetJson('csvimport','/password/dobulkupdate');
        </script>
    </button>
</div>
</fieldset>
</form>

