<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_samba
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<p class="headline">Samba Service Control</p>

<?php 
if (!$this->service->pingZiviosAgent()):
?>
    <div class="dashboarddl">Zivios Agent Status:</div>
    <div class="dashboarddr"><span style="color: red; font-weight: bold;">Offline</span></div>
    <div class="clearline"></div>
    <br />
    <div class="alert">
    Agent on host <b><?php echo $this->service->getMasterComputer()->getdn();?></b> could not be contacted. The agent
    is required for server control and detailed information
    </div>
<?php 
else:
?>
    <div class="dashboarddl">Zivios Agent Status:</div>
    <div class="dashboarddr"><span style="color: green; font-weight: bold;">Online</span></div>
    <div class="clearline"></div>

    <div class="dashboarddl">Samba Service Status:</div>
    <div class="dashboarddr">
        <?php
        if ($this->service->getStatus()) {
            $srvstatus     = '<span style="color: green; font-weight: bold;">Running</span>';
            $serviceOption = 'Stop Service';
        } else {
            $srvstatus     = '<span style="color: red; font-weight: bold;">Stopped</span>';
            $serviceOption = 'Start Service';
        }
        echo $srvstatus;
        ?>
    </div>
    <div class="clearline"></div>

    <div class="dashboarddl">Samba Service Control:</div>
    <div class="dashboarddr">
        <button class="smallbutton" dojoType="dijit.form.Button">Stop
        <script type="dojo/connect" event="onClick">
            zivios.callAction('/samba/service/servicectrl',{
            dn: '<?php echo urlencode($this->service->getdn());?>',
            action: 'stop'},this.id);
        </script>
        </button>
        <button class="smallbutton" dojoType="dijit.form.Button">Start
        <script type="dojo/connect" event="onClick">
            zivios.callAction('/samba/service/servicectrl',{
            dn: '<?php echo urlencode($this->service->getdn());?>',
            action: 'start'},this.id);
        </script>
        </button>

    </div>
    <div class="clearline"></div>

<br />
<p class="headline">Samba Service Information</p>

<div class="dashboarddl">Domain SID : </div>
<div class="dashboarddr"><?php echo $this->service->getProperty('sambasid');?></div> 
                        
<div class="clearline"></div>

<div class="dashboarddl">Master Computer : </div>
<div class="dashboarddr"><?php echo $this->service->getMasterComputer()->getProperty('cn');?></div> 
                        
<div class="clearline"></div>

<?php 
endif;
?>

<style type="text/css">
.dashboarddl {
    float: left; 
    width: 125px;
    padding: 5px;
    clear: left;
    vertical-align: middle;
}

.dashboarddr {
    float: left;
    clear: right;
    padding: 5px;
}

.clearline {
    clear: both;
    border-bottom: 1px solid #e7e7e7;
}
</script>
