<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_ntp
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
 
$this->borderContainer()->captureStart('sambamain', array('design' => 'sidebar', 'style' => 
    'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

$this->contentPane()->captureStart('sambageneral', array('region' => 'left', 
    'style' => 'width: 350px; padding: 0px; margin: 0px; border-left: 0px; border-top: 0px; border-bottom: 0px;',
     'href' => '/samba/service/general/dn/'.urlencode($this->service->getdn())));


echo $this->contentPane()->captureEnd('sambageneral');

$this->contentPane()->captureStart('sambaconfiguration', array('region' => 'center', 
    'style' => 'padding: 0px; margin: 0px; border-left: 0px; border-top: 0px; border-bottom: 0px;',
    'href'  => '/samba/service/configform/dn/'.urlencode($this->service->getdn())));
    

echo $this->contentPane()->captureEnd('sambaconfiguration');

echo $this->borderContainer()->captureEnd('sambamain');
