<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_dns
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<div style="width: 98.3%; border-bottom: 1px solid #477795; 
    background: #7c849c; padding: 5px; color: #fff;"><b>Add a Zone:</b></div>

<div style="padding-left: 10px; border-bottom: 1px solid #e7e7e7;">

    <div style="padding: 5px; float: left;">Select Zone Type: </div>
    <div style="padding: 5px; float: left;">

    <button dojoType="dijit.form.RadioButton" id="forwardzone" name="ztype" checked="checked" value="fzone" type="radio"> 
    <script type="dojo/connect" event="onClick">
    dojo.byId('fwdzone').style.display = 'block';
    dojo.byId('revzone').style.display = 'none';
    </script>
    </button>
    <label for="forwardzone">Forward Zone</label>
            
    <button dojotype="dijit.form.RadioButton" id="reversezone" name="ztype" value="rzone" type="radio">
    <script type="dojo/connect" event="onClick">
    dojo.byId('fwdzone').style.display = 'none';
    dojo.byId('revzone').style.display = 'block';
    </script>
    </button>
    <label for="reversezone"> Reverse Zone</label>
    
    </div>
    <div style="clear: both;"></div>
</div>

<div id="fwdzone" style="display: block;">
<?php echo $this->fwzform; ?>
</div>

<div id="revzone" style="display: none;">
<?php echo $this->rvzform; ?>
</div>

