<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_dns
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/

$this->borderContainer()->captureStart('dnsdashboardlayout', array(
    'design' => 'sidebar',
    'style'  => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

    // Dashboard content panes
    $this->contentPane()->captureStart('dsbleft', array(
        'region'  => 'left',
        'splitter'=> 'false', 
        'style'   => 'width: 300px; padding: 0px; margin: 0px; border-left: 0px; border-top: 0px; border-bottom: 0px;', 
        'href' => '/dns/service/servicecontrol/dn/'.urlencode($this->service->getdn())));
    echo $this->contentPane()->captureEnd('dsbleft');

    $this->contentPane()->captureStart('dsbright', array(
        'region' => 'top',
        'style'  => 'padding: 0px; margin: 0px; border-right: 0px; border-top: 0px; height: 150px; width: 99%;',
        'href' => '/dns/service/addzoneoptions/dn/'.urlencode($this->service->getdn())));
    echo $this->contentPane()->captureEnd('dsbright');

    $this->contentPane()->captureStart('dsbbottom', array(
        'region' => 'center',
        'style' =>'padding: 0px; margin: 0px; border-right: 0px; border-bottom: 0px; width: 99%;', 
        'href' => '/dns/service/searchzoneoptions/dn/'.urlencode($this->service->getdn())));
    echo $this->contentPane()->captureEnd('dsbbottom');

// End border container.
echo $this->borderContainer()->captureEnd('dnsdashboardlayout');
