<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

// start border layout container for group entry.
$this->borderContainer()->captureStart('transaction', array(
    'design' => 'headline', 
    'style' => 'width: 99%; padding: 0px; margin: 0px; border: 0px;'));

// Content pane for group toolbar
$this->contentPane()->captureStart('transdisp', array(
    'region' => 'top',
    'style' => 'padding: 0px; border: 0px; margin: 0px; height: 650px;'));

    $this->tabContainer()->captureStart('transsrvtabs01', array('class' => 'u-tab'));
        $this->contentPane()->captureStart('transmaintab', array(
            'region' => 'center',
            'style'  => 'width: 100%; padding: 0px; margin: 0px; border: 0px;',
            'title' => 'Transaction List',
            'href' => '/transaction/transactionlist'));

            if ($this->id != "") {
                $id = $this->id;
?>
    <script type="dojo/connect" event="onLoad">
        zivios.loadApp('default/transaction/transdetail/id/<?php echo $id;?>',
                      'transsrvtabs01','transdetail<?php echo $id;?>','Transaction #<?php echo $id;?>');
    </script>

<?php
}

            echo $this->contentPane()->captureEnd('transmaintab');
        echo $this->tabContainer()->captureEnd('transsrvtabs01');
echo $this->contentPane()->captureEnd('transdisp');
echo $this->borderContainer()->captureEnd('transaction');

