<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_ntp
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/

// start border layout container for dns entry.
$this->borderContainer()->captureStart('ntpserviceentry', array(
    'design' => 'headline',
    'style'  => 'width: 100%; padding: 0px; margin: 0px; border: 0px;'));

    // Content pane for ntp toolbar
    $this->contentPane()->captureStart('ntpcptb01', array(
        'region' => 'top',
        'style'  => 'width: 100%; height: 26px; padding: 0px; margin: 0px; border: 0px;'));
        echo $this->render('service/toolbar/main.phtml');
    echo $this->contentPane()->captureEnd('ntpcptb01');
    // Content pane for ntp toolbar ends above.

    // Content page for ntp data -- all tabs are auto-generated here, with the ntp
    // dashboard being the default tab which cannot be closed.
    $this->contentPane()->captureStart('ntpdashboard', array(
        'region' => 'center',
        'style' =>'width: 100%; padding: 0px; margin: 0px; border: 0px;'));
        echo $this->render('service/dashboard/main.phtml');
    echo $this->contentPane()->captureEnd('ntpdashboard');
    // Content page for directory data ends above

// End border container layout
echo $this->borderContainer()->captureEnd('ntpserviceentry');
