<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/

Zend_Dojo_View_Helper_Dojo::setUseDeclarative();
$this->dojo()->enable();

// start border layout container for group entry.
$this->borderContainer()->captureStart('aclentry', array('design' => 'headline', 
    'style' => 'width: 99%; padding: 0px; margin: 0px; border: 0px;'));

// Content pane for group toolbar
$this->contentPane()->captureStart('acltb01', array('region' => 'top', 'style' => 'padding: 0px; margin: 0px;'));

echo $this->render('acl/toolbar/main.phtml');

echo $this->contentPane()->captureEnd('acltb01');

$this->contentPane()->captureStart('aclmain',array('region' => 'center', 'style' => 'padding: 0px; margin: 0px;'));


$this->borderContainer()->captureStart('aclbody',array('design' => 'headline', 
    'style' => 'width: 100%; padding: 0px; margin: 0px;'));

$this->contentPane()->captureStart('aclform',array('region' => 'top', 'style' => 'padding: 0px; border: 0px; margin: 0px; height: 100px; border-bottom: 1px solid #ccc;',
                                                   'href' => '/acl/renderform'));

echo $this->contentPane()->captureEnd('aclform');


$this->contentPane()->captureStart('acidisp',array('region' => 'center', 'style' => 'padding: 0px; margin: 0px; border: 0px; height: 300px;', 
                                                   'href' => '/acl/acidisp/dn/'.urlencode($this->entry->getdn())));

echo $this->contentPane()->captureEnd('acidisp');


$this->contentPane()->captureStart('emsacldisp',array('region' => 'bottom', 'style' => 'padding: 0px; margin: 0px; border: 0px; height: 300px; border-top: 1px solid #ccc;', 
    'href' => '/acl/emsacldisp/dn/'.urlencode($this->entry->getdn())));

echo $this->contentPane()->captureEnd('emsacldisp');


echo $this->borderContainer()->captureEnd('aclbody');
echo $this->contentPane()->captureEnd('aclmain');
echo $this->borderContainer()->captureEnd('aclentry');
