<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
?>
<?php
Zend_Dojo_View_Helper_Dojo::setUseDeclarative();
$this->dojo()->enable();
if (isset($this->type)) {
    if ($this->type == 'aci') {
        ?>
        <form action="#" method="post" id="addaciform" dojoType="dijit.form.Form" onsubmit="return false;">
        <input type="hidden" name="dn" value="<?php echo $this->dn;?>"/>
        <div style="padding-left: 5px; width:90%; float: left;">
            <Label for="scope"><B>Scope : </b></label>
            <select id="scope" name="scope" dojoType="dijit.form.FilteringSelect">
            <option value="<?php echo Zivios_Ldap_Aci::SCOPE_ENTRY;?>" selected="selected">Entry Only</option>
            <option value="<?php echo Zivios_Ldap_Aci::SCOPE_SUBTREE;?>">Sub Tree</option>
            </select>
        
            <label for="aciaction"><b>Action : </b></label>
            <select name="aciaction" dojoType="dijit.form.FilteringSelect">
            <option value="<?php echo Zivios_Ldap_Aci::ACTION_GRANT;?>" selected="selected">Grant</option>
            <option value="<?php echo Zivios_Ldap_Aci::ACTION_DENY;?>"> Deny </option>
            </select>
        </div>
        <div style="clear: both;"></div>
        <div style="padding-left: 5px; width:90%; float: left;">
            <Label for="perms"><B>Permissions :</b> </label>
            <input type="checkbox" dojoType="dijit.form.CheckBox" name="perms[]" value="<?php echo Zivios_Ldap_Aci::PERM_R;?>">Read</input>
            <input type="checkbox" dojoType="dijit.form.CheckBox" name="perms[]" value="<?php echo Zivios_Ldap_Aci::PERM_W;?>">Write</input>
            <input type="checkbox" dojoType="dijit.form.CheckBox" name="perms[]" value="<?php echo Zivios_Ldap_Aci::PERM_S;?>">Search</input>
            <input type="checkbox" dojoType="dijit.form.CheckBox" name="perms[]" value="<?php echo Zivios_Ldap_Aci::PERM_C;?>">Compare</input>
            <input type="checkbox" dojoType="dijit.form.CheckBox" name="perms[]" value="<?php echo Zivios_Ldap_Aci::PERM_X;?>">Auth</input>
        </div>
        
       <div style="clear: both;"></div>
       <div style="padding-left: 5px; width:300px; float: left;">
            <Label for="appliesto"><B> Applies to :</b> </label>
            <select name="appliesto" dojoType="dijit.form.FilteringSelect">
                <script type="dojo/method" event="onChange">
                    userac = document.getElementById('userac');
                    display = userac.style.display;
                    if (this.value == '<?php echo Zivios_Ldap_Aci::TYPE_ACCESS_ID;?>' && display == 'none') {
                        dojo.fx.wipeIn({
                                       node: "userac",
                                       duration: 300}).play();
                    } else if (display != 'none') {
                        dojo.fx.wipeOut({
                                        node: "userac",
                                        duration: 300}).play();
                    }
                </script>
            <option value="<?php echo Zivios_Ldap_Aci::TYPE_PUBLIC;?>" selected="selected">Everyone</option>
            <option value="<?php echo Zivios_Ldap_Aci::TYPE_SELF;?>"> Self </option>
            <option value="<?php echo Zivios_Ldap_Aci::TYPE_ACCESS_ID;?>"> User </option>
            </select>
            </div>
            <div id="userac" style="display: none; float: left; width: 300px;">
            <div dojoType="zivios.AutocompleteReadStore" jsId="stateStore" url="/acl/getallusers"></div>
            <b>User Search: </b> 
            <input dojoType="dijit.form.FilteringSelect" value="" store="stateStore" name="user" id="user" required="false">
            </div>
            <div style="clear: both;"></div>
            <div style="padding-left: 5px; width: 300px; float: left;">
            <button id="addaciform-submit" dojoType="dijit.form.Button" label="Add Acl">
                <script type="dojo/method" event="onClick"> 
                    zivios.formXhrPost('addaciform', '/default/acl/doaddaci');
                </script>
            </button>
            </div>
            
            </form>
        
        <?php
    }
    else if ($this->type == 'emsacl') {
        ?>
        <form action="#" method="post" id="addaclform" dojoType="dijit.form.Form" onsubmit="return false;">
        <input type="hidden" name="dn" value="<?php echo $this->dn;?>"/>
        <div style="padding-left: 5px; width:90%; float: left;">
            <Label for="scope"><B>Scope : </b></label>
            <select id="scope" name="scope" dojoType="dijit.form.FilteringSelect">
            <option value="<?php echo Zivios_Acl::SCOPE_ENTRY;?>" selected="selected">Entry Only</option>
            <option value="<?php echo Zivios_Acl::SCOPE_SUBTREE;?>">Sub Tree</option>
            </select>
        
            <label for="aclaction"><b>Action : </b></label>
            <select name="aclaction" dojoType="dijit.form.FilteringSelect">
            <option value="<?php echo Zivios_Acl::ACTION_GRANT;?>" selected="selected">Grant</option>
            <option value="<?php echo Zivios_Acl::ACTION_DENY;?>"> Deny </option>
            </select>
        </div>
        <div style="clear: both;"></div>
        <div style="padding-left: 5px; width:90%; float: left;">
            <Label for="acl"><B>Zivios ACL :</b> </label>
            <input type="text" dojoType="dijit.form.ValidationTextBox" name="acl" id="acl" 
            regExp="[\w\_]+" required="true" invalidMessage="Invalid Zivios ACL Format"/>
        </div>
        
       <div style="clear: both;"></div>
       <div style="padding-left: 5px; width:300px; float: left;">
            <Label for="appliesto"><B> Applies to :</b> </label>
            <select name="appliesto" dojoType="dijit.form.FilteringSelect">
                <script type="dojo/method" event="onChange">
                    userac = document.getElementById('userac');
                    display = userac.style.display;
                    if (this.value == '<?php echo Zivios_Acl::SUBJECT_USER;?>' && display == 'none') {
                        dojo.fx.wipeIn({
                                       node: "userac",
                                       duration: 300}).play();
                    } else if (display != 'none') {
                        dojo.fx.wipeOut({
                                        node: "userac",
                                        duration: 300}).play();
                    }
                </script>
            <option value="<?php echo Zivios_Acl::SUBJECT_ALL;?>" selected="selected">Everyone</option>
            <option value="<?php echo Zivios_Acl::SUBJECT_SELF;?>"> Self </option>
            <option value="<?php echo Zivios_Acl::SUBJECT_USER;?>"> User </option>
            </select>
            </div>
            <div id="userac" style="display: none; float: left; width: 300px;">
            <div dojoType="zivios.AutocompleteReadStore" jsId="stateStore" url="/acl/getallusers"></div>
            <b>User Search: </b> 
            <input dojoType="dijit.form.FilteringSelect" value="" store="stateStore" name="user" id="user" required="false">
            </div>
            <div style="clear: both;"></div>
            <div style="padding-left: 5px; width: 300px; float: left;">
            <button id="addaclform-submit" dojoType="dijit.form.Button" label="Add Acl">
                <script type="dojo/method" event="onClick"> 
                    zivios.formXhrPost('addaclform', '/default/acl/doaddacl');
                </script>
            </button>
            </div>
            
            </form>
        <?php
    }
}
else {
    ?>
    <div class="note">
    <br >ACL's that apply to this object are displayed below. To add a new Zivios or OpenLdap 
    ACL please use the toolbar above
    </div>
    <?php 
}
?>
