<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<div class="heading">Search for Users</div>
<div class="content">

<div class="info infocl" style="width: 350px;">Search for existing group members or group non-members.</div>

<div class="zflabel" style="width: 100px;">User Filter: </div>

<input type="text" name="filter" value=""
        dojoType="dijit.form.TextBox"
        trim="true" id="filter"
        propercase="true" class="zfgenField" />
<div class="cboth"></div>

<div class="zflabel" style="width: 100px;">&nbsp;</div>

<select dojoType="dojox.form.DropDownSelect" id="searchtype" name="searchtype" size="10" value="members">
  <option value="members" selected="selected">Members</option>
  <option value="nonmembers">Non Members</option>
</select>

<button dojoType="dijit.form.Button" id="search">Search
    <script type="dojo/method" event="onClick">
         var filter = dijit.byId('filter').value;
         var type = dijit.byId('searchtype').value;
         var resultspane = dijit.byId('searchresults');
         resultspane.href = "/group/search/dn/<?php echo urlencode($this->entry->getdn());?>/filter/"+filter+"/type/"+type;
         resultspane.refresh();
    </script>
</button>

</div>

