<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     Zivios
 * @copyright   Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>
<p class="headline">Squid User Configuration</p>

<div class="floatleft" style="width: 350px; border-right: 1px solid #e5e5e5">
    <?php echo $this->form; ?>
</div>

<div class="floatleft" style="padding-left: 5px;">
    <div class="note notecl" style="width: 300px;">
    Please note that a whitelist and blacklist cannot be defined simultaneously. 
    You must either define a whitelist or a blacklist. 
   </div>
</div>

<div class="clearboth"></div>
