<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package     mod_openldap
 * @copyright   Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license     http://www.zivios.org/legal/license
 **/
?>

<div class="heading">No Compatible Computers</div>
<div class="content">
    It appears that no compatible computers are available on your network for Zivios
    Directory Service Replica deployment. 
</div>
<div class="subheading">Compatible Computer Listing</div>
<div class="content">
    Below is a list of compatible operating systems for the Zivios Directory Service: 
    <ul>
    <?php
    foreach ($this->replicaCompatible as $distro) {
        echo '<li/>' . $distro;
    }
    ?>
    </ul>
</div>
