<?php
/**
 * Copyright (c) 2008 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		mod_samba
 * @copyright	Copyright (c) 2008 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 * @version		$Id$
 * @lastchangeddate $LastChangedDate$
 **/
?>

<script>
SambaControlAction = function (action) {
    form = document.getElementById('servstat');
    form.action.value = action;

    control = document.getElementById('control');
    control.innerHTML='<b>Processing... Please Wait</b>';

    if (action == 'refresh') {

        callAction('/mail/service/status/','pgupdate','<?=$this->obj->getdn()?>');
    }
    else {
       callAjaxRender('servstat','/samba/service/dashview','pgupdate');
    }


}
</script>

<div style="padding-left: 10px;">
		<div style="width: 140px;" class="floatleft">Master Computer</div>
		<div style="width: 350px;" class="floatleft">
			<a href="#" onclick="javascript:nodeDetails('<?php
				echo $this->masterComputer->getdn();
				?>'); return false;"><img src="<?php echo $this->imgBase; ?>/icons/server.png" align="absmiddle"/>
				<?php echo $this->masterComputer->getProperty("cn");?></a>
		</div>
		<div class="clear"></div>
		<div style="width: 140px;" class="floatleft">Service Status</div>
		<div style="width: 350px;" class="floatleft" id="control">
		<?php
			if ($this->status) {
				echo '<span style="color: green; font-weight: bold;">Running</span>';
				echo '  [<a href="#" onclick="javascript:SambaControlAction(\'stop\');">Stop Service</a>]';
			} else {
				echo '<span style="color: red; font-weight: bold;">Stopped</span>';
				echo '  [<a href="#" onclick="javascript:SambaControlAction(\'start\'); return false;">Start Service</a>]';
			}

		?></div>
		<div class="clear"></div>

		 [<a href="#" onclick="javascript:nodeDetails('<?php echo $this->obj->getdn(); ?>'); return false;">Update</a>]</div>
		<div class="floatleft"></div>
		<div class="clear"></div>
	</div>

<form id="servstat">
<input type="hidden" name="operate_dn" value="<?php echo $this->obj->getdn();?>" />
<input type="hidden" name="action" value="install" />
</form>
