<?php
/**
 * Copyright (c) 2008-2010 Zivios, LLC.
 *
 * This file is part of Zivios.
 *
 * Zivios is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Zivios is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Zivios.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package		Zivios
 * @copyright	Copyright (c) 2008-2010 Zivios, LLC. (http://www.zivios.org)
 * @license		http://www.zivios.org/legal/license
 **/
?>
<div class="note">

<P class="heading">
Delete Group <B><?php echo $this->entry->getProperty('cn');?></b>
</P>

You are about to delete the group with DN : <?php echo $this->entry->getdn();?>
<br />
<div class="floatleft" style="width: 100px; text-align: center;">
    <button dojoType="dijit.form.Button" id="confirm">Delete
        <script type="dojo/method" event="onClick">
        zivios.callAction('/default/group/delete',{ confirm: true, dn: '<?php echo $this->entry->getdn();?>'},'confirm');
        </script>
    </button>
    </div>
    <div style="clear: both;"></div>
</div>

